/**
 * Curated research priors — compiled from official docs research.
 * The agent merges live fetch signals with these priors.
 * Human verification samples against live docs (see data/verification.json).
 */

/** @type {Record<number, object>} */
export const PRIORS = {
  1: {
    one_liner: "Enterprise CRM platform for sales, service, and custom business apps.",
    auth: ["OAuth2"],
    access: "self_serve",
    access_detail: "Free Developer Edition / Trailhead orgs; OAuth connected apps are self-serve.",
    api_surface: "REST + GraphQL + Bulk/SOAP (very broad)",
    api_breadth: "broad",
    mcp: "community",
    mcp_detail: "No first-party MCP required for toolkit; large REST surface.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_what_is_rest_api.htm"],
    confidence: 0.95,
  },
  2: {
    one_liner: "Inbound CRM, marketing, and service hub with a large public API.",
    auth: ["OAuth2", "Token"],
    access: "self_serve",
    access_detail: "Free developer account; private apps / OAuth apps create tokens in-portal.",
    api_surface: "REST (broad CRM + marketing + CMS)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP; excellent REST docs.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developers.hubspot.com/docs/api/overview"],
    confidence: 0.96,
  },
  3: {
    one_liner: "Sales CRM focused on pipeline deals and activity tracking.",
    auth: ["OAuth2", "API key"],
    access: "self_serve",
    access_detail: "API tokens from settings; OAuth for public apps.",
    api_surface: "REST (moderate–broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developers.pipedrive.com/docs/api/v1"],
    confidence: 0.94,
  },
  4: {
    one_liner: "Modern relationship CRM with flexible data model and strong API.",
    auth: ["OAuth2", "API key"],
    access: "self_serve",
    access_detail: "API keys and OAuth apps from Attio developer settings.",
    api_surface: "REST (moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developers.attio.com/docs"],
    confidence: 0.93,
  },
  5: {
    one_liner: "Open-source CRM; self-host or cloud with GraphQL API.",
    auth: ["API key", "Token"],
    access: "self_serve",
    access_detail: "Open-source; self-host for free or use Twenty cloud.",
    api_surface: "GraphQL (core CRM objects)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://docs.twenty.com/developers/api-and-webhooks/api"],
    confidence: 0.9,
  },
  6: {
    one_liner: "Citrix work platform / flexible apps and CRM-like workspaces.",
    auth: ["OAuth2"],
    access: "self_serve",
    access_detail: "OAuth client registration via Podio developer site.",
    api_surface: "REST (moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developers.podio.com/doc/authentication"],
    confidence: 0.88,
  },
  7: {
    one_liner: "Zoho's CRM suite with multi-region OAuth and REST APIs.",
    auth: ["OAuth2"],
    access: "self_serve",
    access_detail: "Zoho API console; free CRM trial supports API access.",
    api_surface: "REST (broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://www.zoho.com/crm/developer/docs/api/v6/"],
    confidence: 0.93,
  },
  8: {
    one_liner: "Sales engagement CRM with simple API-key auth.",
    auth: ["API key"],
    access: "trial_or_paid_self_serve",
    access_detail: "API key in settings; product is paid with trial.",
    api_surface: "REST (moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developer.close.com/"],
    confidence: 0.92,
  },
  9: {
    one_liner: "Google Workspace–centric CRM (formerly ProsperWorks).",
    auth: ["OAuth2", "API key"],
    access: "trial_or_paid_self_serve",
    access_detail: "Developer API keys for Copper accounts; paid product.",
    api_surface: "REST (moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developer.copper.com/"],
    confidence: 0.9,
  },
  10: {
    one_liner: "Enterprise deal / relationship intelligence CRM (Intapp).",
    auth: ["OAuth2", "API key"],
    access: "admin",
    access_detail: "Needs DealCloud tenant; API capability enabled by admin/CSM. MCP client preview noted for 2026.",
    api_surface: "REST (broad enterprise data model)",
    api_breadth: "broad",
    mcp: "preview",
    mcp_detail: "DealCloud MCP server — client preview starting July 2026 (per docs).",
    buildability: "partial",
    blocker: "Requires existing enterprise tenant + admin API enablement; not a free self-serve sandbox.",
    evidence: ["https://api.docs.dealcloud.com/docs/apikeys", "https://api.docs.dealcloud.com/docs/token"],
    confidence: 0.91,
  },
  11: {
    one_liner: "Customer support ticketing and help-center platform.",
    auth: ["OAuth2", "Token", "Basic"],
    access: "self_serve",
    access_detail: "Trial Zendesk Support; API tokens and OAuth apps.",
    api_surface: "REST (broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developer.zendesk.com/api-reference/introduction/security-and-auth/"],
    confidence: 0.95,
  },
  12: {
    one_liner: "Customer messaging and support platform.",
    auth: ["OAuth2", "Token"],
    access: "self_serve",
    access_detail: "Developer hub; access tokens and OAuth.",
    api_surface: "REST (broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developers.intercom.com/docs"],
    confidence: 0.94,
  },
  13: {
    one_liner: "Freshworks helpdesk with ticket/contact APIs.",
    auth: ["API key"],
    access: "self_serve",
    access_detail: "API key from profile; free trial available.",
    api_surface: "REST (moderate–broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developers.freshdesk.com/api/"],
    confidence: 0.93,
  },
  14: {
    one_liner: "Shared inbox / customer ops platform.",
    auth: ["OAuth2", "Token"],
    access: "trial_or_paid_self_serve",
    access_detail: "API tokens and OAuth; paid product with trial.",
    api_surface: "REST (moderate–broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://dev.frontapp.com/docs/getting-started"],
    confidence: 0.92,
  },
  15: {
    one_liner: "B2B support platform (Slack-native) with REST API and hosted MCP.",
    auth: ["Token", "OAuth2"],
    access: "admin",
    access_detail: "API bearer tokens created by Admins; MCP uses OAuth at mcp.usepylon.com.",
    api_surface: "REST + official MCP",
    api_breadth: "moderate",
    mcp: "official",
    mcp_detail: "Official Pylon MCP (OAuth) — https://mcp.usepylon.com",
    buildability: "ready",
    blocker: null,
    evidence: [
      "https://docs.usepylon.com/pylon-docs/developer/api/authentication",
      "https://docs.usepylon.com/pylon-docs/integrations/pylon-mcp",
    ],
    confidence: 0.94,
  },
  16: {
    one_liner: "Omnichannel live chat and helpdesk.",
    auth: ["API key"],
    access: "self_serve",
    access_detail: "API key from LiveAgent panel; free trial.",
    api_surface: "REST (moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://support.liveagent.com/741170-REST-API"],
    confidence: 0.88,
  },
  17: {
    one_liner: "Modern B2B support tool with GraphQL API.",
    auth: ["API key"],
    access: "trial_or_paid_self_serve",
    access_detail: "API keys in workspace settings; product is paid.",
    api_surface: "GraphQL",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://www.plain.com/docs/graphql/authentication"],
    confidence: 0.9,
  },
  18: {
    one_liner: "Shared inbox and customer messaging for support teams.",
    auth: ["OAuth2"],
    access: "self_serve",
    access_detail: "OAuth2 Mailbox API; free plan exists.",
    api_surface: "REST (moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developer.helpscout.com/mailbox-api/overview/authentication/"],
    confidence: 0.91,
  },
  19: {
    one_liner: "Ecommerce-focused helpdesk.",
    auth: ["Basic", "API key"],
    access: "trial_or_paid_self_serve",
    access_detail: "HTTP Basic with API key; needs Gorgias account.",
    api_surface: "REST (moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developers.gorgias.com/reference/authentication"],
    confidence: 0.9,
  },
  20: {
    one_liner: "Enterprise customer service platform (side conversations, etc.).",
    auth: ["Basic", "Token"],
    access: "partner",
    access_detail: "Enterprise product; API access typically via customer/partner engagement.",
    api_surface: "REST (moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "partial",
    blocker: "Hard to get a free sandbox without being a Gladly customer.",
    evidence: ["https://developer.gladly.com/rest/"],
    confidence: 0.82,
  },
  21: {
    one_liner: "Team messaging with mature Web API and events.",
    auth: ["OAuth2", "Token"],
    access: "self_serve",
    access_detail: "Create Slack app + bot/user tokens free.",
    api_surface: "REST + Events/Socket Mode (broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "Classic Slack Web API is toolkit-ready; no first-party MCP required for coverage.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://api.slack.com/authentication"],
    confidence: 0.96,
  },
  22: {
    one_liner: "Programmable SMS, voice, WhatsApp, and communications APIs.",
    auth: ["API key", "Basic", "Token"],
    access: "self_serve",
    access_detail: "Free trial credit; Account SID + Auth Token.",
    api_surface: "REST (very broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP required.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://www.twilio.com/docs/usage/api"],
    confidence: 0.97,
  },
  23: {
    one_liner: "Zoho team chat / collaboration messenger.",
    auth: ["OAuth2"],
    access: "self_serve",
    access_detail: "Zoho API console OAuth for Cliq.",
    api_surface: "REST (moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://www.zoho.com/cliq/help/restapi/"],
    confidence: 0.88,
  },
  24: {
    one_liner: "Lark/Feishu suite open platform (chat, docs, calendar).",
    auth: ["OAuth2", "Token"],
    access: "self_serve",
    access_detail: "Create app on open.larksuite.com; tenant admin may need to approve.",
    api_surface: "REST (broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "partial",
    blocker: "Tenant admin approval often required for production scopes.",
    evidence: ["https://open.larksuite.com/document/"],
    confidence: 0.87,
  },
  25: {
    one_liner: "Team chat (CAKE.com) with REST API.",
    auth: ["API key", "Token"],
    access: "self_serve",
    access_detail: "API access from Pumble workspace settings.",
    api_surface: "REST (narrow–moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://pumble.com/help/integrations/api/"],
    confidence: 0.8,
  },
  26: {
    one_liner: "Gaming/community chat platform with Bot API.",
    auth: ["OAuth2", "Token"],
    access: "self_serve",
    access_detail: "Discord Developer Portal; bot tokens free.",
    api_surface: "REST + Gateway (broad)",
    api_breadth: "broad",
    mcp: "community",
    mcp_detail: "Community MCP servers exist; official is REST/Gateway.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://discord.com/developers/docs/topics/oauth2"],
    confidence: 0.95,
  },
  27: {
    one_liner: "Messaging app with Bot API for bots (not user MTProto for agents typically).",
    auth: ["Token"],
    access: "self_serve",
    access_detail: "BotFather issues bot tokens instantly for free.",
    api_surface: "HTTPS Bot API (broad for bots)",
    api_breadth: "broad",
    mcp: "community",
    mcp_detail: "Community MCP wrappers; official Bot API is enough.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://core.telegram.org/bots/api"],
    confidence: 0.96,
  },
  28: {
    one_liner: "WhatsApp Cloud API for business messaging via Meta.",
    auth: ["OAuth2", "Token"],
    access: "partner",
    access_detail: "Cloud API usable for own WABA; multi-tenant/solution-provider path needs App Review + Advanced Access.",
    api_surface: "REST (messaging + templates + webhooks)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "partial",
    blocker: "Business verification + phone number; solution-provider toolkit needs Meta App Review.",
    evidence: ["https://developers.facebook.com/docs/whatsapp/cloud-api/get-started"],
    confidence: 0.92,
  },
  29: {
    one_liner: "Cloud phone system / call center API.",
    auth: ["OAuth2", "API key"],
    access: "trial_or_paid_self_serve",
    access_detail: "API keys / OAuth for Aircall customers.",
    api_surface: "REST (moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developer.aircall.io/api-references/"],
    confidence: 0.9,
  },
  30: {
    one_liner: "Vonage (Nexmo) communications APIs — SMS, voice, video.",
    auth: ["API key", "Token", "Basic"],
    access: "self_serve",
    access_detail: "Free trial credit; API key/secret in dashboard.",
    api_surface: "REST (broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developer.vonage.com/en/getting-started/overview"],
    confidence: 0.94,
  },
  31: {
    one_liner: "Google Ads campaign management API.",
    auth: ["OAuth2"],
    access: "partner",
    access_detail: "Needs Google Ads developer token; production access is application/review gated.",
    api_surface: "gRPC/REST (very broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "partial",
    blocker: "Developer token + basic/standard access review for production.",
    evidence: ["https://developers.google.com/google-ads/api/docs/start"],
    confidence: 0.93,
  },
  32: {
    one_liner: "Meta Marketing API for Facebook/Instagram ads.",
    auth: ["OAuth2", "Token"],
    access: "partner",
    access_detail: "App Review / Advanced Access for many ad insights and management scopes.",
    api_surface: "REST Graph API (broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "partial",
    blocker: "App Review and Business verification for meaningful production scopes.",
    evidence: ["https://developers.facebook.com/docs/marketing-apis/get-started"],
    confidence: 0.93,
  },
  33: {
    one_liner: "LinkedIn Marketing / Ads API.",
    auth: ["OAuth2"],
    access: "partner",
    access_detail: "Development tier limited; Standard access requires LinkedIn application/approval.",
    api_surface: "REST (ads + creatives + reporting)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "partial",
    blocker: "Partner/access-tier upgrade beyond single-ad-account development.",
    evidence: ["https://learn.microsoft.com/en-us/linkedin/marketing/overview"],
    confidence: 0.91,
  },
  34: {
    one_liner: "GoHighLevel CRM/marketing automation platform API.",
    auth: ["OAuth2", "API key"],
    access: "trial_or_paid_self_serve",
    access_detail: "Agency/sub-account; OAuth and API keys documented on Stoplight.",
    api_surface: "REST (broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://highlevel.stoplight.io/docs/integrations"],
    confidence: 0.88,
  },
  35: {
    one_liner: "Email marketing and audience platform.",
    auth: ["OAuth2", "API key"],
    access: "self_serve",
    access_detail: "Free Marketing API key / OAuth from account.",
    api_surface: "REST (broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://mailchimp.com/developer/marketing/guides/quick-start/"],
    confidence: 0.95,
  },
  36: {
    one_liner: "Ecommerce email/SMS marketing platform.",
    auth: ["OAuth2", "API key"],
    access: "self_serve",
    access_detail: "Private API keys and OAuth; free account can start.",
    api_surface: "REST (broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developers.klaviyo.com/en/docs/authenticate_"],
    confidence: 0.94,
  },
  37: {
    one_liner: "Funnel builder / course & marketing platform.",
    auth: ["API key"],
    access: "trial_or_paid_self_serve",
    access_detail: "Public developer docs; API key from account (product paid).",
    api_surface: "REST (narrow–moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "partial",
    blocker: "Docs/surface thinner than major ESPs; confirm endpoint coverage for toolkit scope.",
    evidence: ["https://developer.systeme.io/"],
    confidence: 0.75,
  },
  38: {
    one_liner: "Pinterest API for pins, boards, and ads.",
    auth: ["OAuth2"],
    access: "partner",
    access_detail: "App review / trial access for many production scopes.",
    api_surface: "REST (moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "partial",
    blocker: "Access tiers and app review for ads/write scopes.",
    evidence: ["https://developers.pinterest.com/docs/getting-started/set-up-app/"],
    confidence: 0.88,
  },
  39: {
    one_liner: "Meta Threads API for posting and reading Threads content.",
    auth: ["OAuth2"],
    access: "self_serve",
    access_detail: "Meta app with Threads use case; publish requirements for non-owned data.",
    api_surface: "REST (narrow–moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developers.facebook.com/docs/threads/get-started"],
    confidence: 0.9,
  },
  40: {
    one_liner: "Transactional email API (Twilio SendGrid).",
    auth: ["API key"],
    access: "self_serve",
    access_detail: "Free tier; API keys in SendGrid UI.",
    api_surface: "REST (moderate–broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://www.twilio.com/docs/sendgrid/api-reference"],
    confidence: 0.96,
  },
  41: {
    one_liner: "Ecommerce platform with Admin/Storefront GraphQL and REST.",
    auth: ["OAuth2", "Token"],
    access: "self_serve",
    access_detail: "Partner Dashboard + dev stores; custom apps get Admin API tokens.",
    api_surface: "GraphQL + REST (very broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP; GraphQL Admin is toolkit gold.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://shopify.dev/docs/api/admin-graphql"],
    confidence: 0.96,
  },
  42: {
    one_liner: "WordPress ecommerce plugin with REST API.",
    auth: ["OAuth2", "Basic", "API key"],
    access: "self_serve",
    access_detail: "Generate keys in WooCommerce settings on any store.",
    api_surface: "REST (broad store objects)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://woocommerce.github.io/woocommerce-rest-api-docs/"],
    confidence: 0.95,
  },
  43: {
    one_liner: "SaaS ecommerce platform with REST management APIs.",
    auth: ["OAuth2", "API key"],
    access: "self_serve",
    access_detail: "Store API accounts / OAuth in BigCommerce control panel.",
    api_surface: "REST (broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developer.bigcommerce.com/docs/start/authentication"],
    confidence: 0.93,
  },
  44: {
    one_liner: "Salesforce B2C/B2B Commerce (Commerce Cloud) APIs.",
    auth: ["OAuth2"],
    access: "partner",
    access_detail: "Needs Commerce Cloud instance; typically customer/partner provisioned.",
    api_surface: "SCAPI REST (broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "partial",
    blocker: "No free self-serve production-like tenant for most builders.",
    evidence: ["https://developer.salesforce.com/docs/commerce/commerce-api/overview"],
    confidence: 0.88,
  },
  45: {
    one_liner: "Adobe Commerce / Magento Open Source web APIs.",
    auth: ["OAuth2", "Token", "Basic"],
    access: "self_serve",
    access_detail: "Open Source self-host; Adobe Commerce is licensed.",
    api_surface: "REST + GraphQL (broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developer.adobe.com/commerce/webapi/get-started/"],
    confidence: 0.9,
  },
  46: {
    one_liner: "Website builder with Commerce APIs.",
    auth: ["OAuth2"],
    access: "trial_or_paid_self_serve",
    access_detail: "OAuth apps; commerce APIs for Squarespace stores.",
    api_surface: "REST (narrow–moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "partial",
    blocker: "Narrower surface than Shopify/BigCommerce; paid store needed.",
    evidence: ["https://developers.squarespace.com/commerce-apis/authentication"],
    confidence: 0.86,
  },
  47: {
    one_liner: "Embeddable ecommerce (Lightspeed) with REST API.",
    auth: ["OAuth2", "Token"],
    access: "self_serve",
    access_detail: "API access via Ecwid/Lightspeed account.",
    api_surface: "REST (moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://api-docs.ecwid.com/"],
    confidence: 0.88,
  },
  48: {
    one_liner: "Creator commerce / digital products platform.",
    auth: ["Token"],
    access: "self_serve",
    access_detail: "Access token from Gumroad settings; free to create account.",
    api_surface: "REST (narrow–moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://gumroad.com/api"],
    confidence: 0.9,
  },
  49: {
    one_liner: "Amazon Selling Partner API for marketplace sellers/vendors.",
    auth: ["OAuth2"],
    access: "partner",
    access_detail: "Developer profile + app registration; roles/policies approval.",
    api_surface: "REST (very broad SP-API)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "partial",
    blocker: "Amazon developer registration and role approval friction.",
    evidence: ["https://developer-docs.amazon.com/sp-api/docs/registering-your-application"],
    confidence: 0.92,
  },
  50: {
    one_liner: "Creator payments / checkout infrastructure.",
    auth: ["API key"],
    access: "self_serve",
    access_detail: "x-api-key from FanBasis dashboard; sandbox available.",
    api_surface: "REST (moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://apidocs.fan/"],
    confidence: 0.9,
  },
  51: {
    one_liner: "SEO & SERP data API marketplace.",
    auth: ["Basic", "API key"],
    access: "self_serve",
    access_detail: "Pay-as-you-go; login creates API credentials.",
    api_surface: "REST (very broad SEO endpoints)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://docs.dataforseo.com/v3/"],
    confidence: 0.94,
  },
  52: {
    one_liner: "SEO platform with rank tracking and site audit APIs.",
    auth: ["API key"],
    access: "paid",
    access_detail: "API on paid SE Ranking plans.",
    api_surface: "REST (moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "partial",
    blocker: "Paid plan required for meaningful API use.",
    evidence: ["https://seranking.com/api.html"],
    confidence: 0.86,
  },
  53: {
    one_liner: "SEO data platform with API v3 and hosted MCP.",
    auth: ["API key", "OAuth2"],
    access: "paid",
    access_detail: "API/MCP on Lite+ paid plans; free test queries limited.",
    api_surface: "REST + official MCP",
    api_breadth: "broad",
    mcp: "official",
    mcp_detail: "Hosted Ahrefs MCP at api.ahrefs.com/mcp — consumes API units.",
    buildability: "partial",
    blocker: "Paid plan (Lite+) required for real API/MCP usage.",
    evidence: ["https://docs.ahrefs.com/en/api/docs/introduction", "https://docs.ahrefs.com/en/mcp/docs/introduction"],
    confidence: 0.94,
  },
  54: {
    one_liner: "Web scraping / automation API service.",
    auth: ["API key", "Token"],
    access: "self_serve",
    access_detail: "Docs at docs.mrscraper.com; signup for API access.",
    api_surface: "REST (moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://docs.mrscraper.com/"],
    confidence: 0.8,
  },
  55: {
    one_liner: "Actor-based web scraping and automation platform.",
    auth: ["API key", "Token"],
    access: "self_serve",
    access_detail: "Free tier; API tokens in Apify console.",
    api_surface: "REST (broad) + Actors",
    api_breadth: "broad",
    mcp: "official",
    mcp_detail: "Apify maintains MCP-oriented tooling / integrations.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://docs.apify.com/api/v2"],
    confidence: 0.94,
  },
  56: {
    one_liner: "LLM-oriented web crawling and extraction API.",
    auth: ["API key"],
    access: "self_serve",
    access_detail: "Free credits on signup; API key in dashboard.",
    api_surface: "REST + MCP",
    api_breadth: "moderate",
    mcp: "official",
    mcp_detail: "Official Firecrawl MCP server widely documented.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://docs.firecrawl.dev/"],
    confidence: 0.95,
  },
  57: {
    one_liner: "Proxy, scraping, and SERP datasets platform.",
    auth: ["API key", "Token"],
    access: "trial_or_paid_self_serve",
    access_detail: "Signup + zones/API tokens; commercial pricing.",
    api_surface: "REST / proxy APIs (broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No primary MCP focus.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://docs.brightdata.com/"],
    confidence: 0.9,
  },
  58: {
    one_liner: "Open-source username hunt across social sites (CLI, not SaaS API).",
    auth: ["Other"],
    access: "self_serve",
    access_detail: "MIT open-source; clone and run locally — no vendor credentials.",
    api_surface: "CLI / Python (not a hosted REST API)",
    api_breadth: "narrow",
    mcp: "community",
    mcp_detail: "Could wrap as a local skill/MCP; no vendor API.",
    buildability: "partial",
    blocker: "Not a networked SaaS API — toolkit would wrap CLI/local process.",
    evidence: ["https://github.com/sherlock-project/sherlock"],
    confidence: 0.97,
  },
  59: {
    one_liner: "Contact/company enrichment and prospecting API.",
    auth: ["API key"],
    access: "partner",
    access_detail: "API key provided via contract (docs: key from contract).",
    api_surface: "REST (enrichment/prospector)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "blocked",
    blocker: "Contract-gated API keys — outreach required.",
    evidence: ["https://docs.waterfall.io/v1/authentication", "https://docs.waterfall.io/v1/introduction"],
    confidence: 0.9,
  },
  60: {
    one_liner: "GTM data enrichment workbook platform.",
    auth: ["API key", "Other"],
    access: "partner",
    access_detail: "Clay HTTP API / webhooks exist for customers; broad public self-serve API is limited vs product UI.",
    api_surface: "HTTP API / webhooks (narrow vs UI)",
    api_breadth: "narrow",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "partial",
    blocker: "Product is UI-first; public agent toolkit surface is thinner and account-gated.",
    evidence: ["https://www.clay.com/university/guide/http-api-integration-overview"],
    confidence: 0.78,
  },
  61: {
    one_liner: "Source control and DevOps platform with excellent REST/GraphQL APIs.",
    auth: ["OAuth2", "Token"],
    access: "self_serve",
    access_detail: "PATs and GitHub Apps free.",
    api_surface: "REST + GraphQL (very broad)",
    api_breadth: "broad",
    mcp: "official",
    mcp_detail: "GitHub official remote MCP server available.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://docs.github.com/en/rest/authentication/authenticating-to-the-rest-api"],
    confidence: 0.98,
  },
  62: {
    one_liner: "Frontend cloud deployment platform.",
    auth: ["Token", "OAuth2"],
    access: "self_serve",
    access_detail: "Personal tokens from Vercel dashboard; free hobby tier.",
    api_surface: "REST (moderate–broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP required.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://vercel.com/docs/rest-api"],
    confidence: 0.95,
  },
  63: {
    one_liner: "JAMstack hosting and deploy platform.",
    auth: ["Token", "OAuth2"],
    access: "self_serve",
    access_detail: "Personal access tokens; free tier.",
    api_surface: "REST (moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://docs.netlify.com/api/get-started/"],
    confidence: 0.94,
  },
  64: {
    one_liner: "CDN, DNS, security, and edge compute APIs.",
    auth: ["API key", "Token", "OAuth2"],
    access: "self_serve",
    access_detail: "API tokens free with Cloudflare account.",
    api_surface: "REST (very broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP focus.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developers.cloudflare.com/fundamentals/api/get-started/"],
    confidence: 0.96,
  },
  65: {
    one_liner: "Postgres backend-as-a-service with Auth, Storage, Realtime.",
    auth: ["API key", "Token", "OAuth2"],
    access: "self_serve",
    access_detail: "Free project; service role / anon keys.",
    api_surface: "REST + JS client (broad)",
    api_breadth: "broad",
    mcp: "official",
    mcp_detail: "Supabase MCP server exists for agent tooling.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://supabase.com/docs/reference/api/introduction"],
    confidence: 0.95,
  },
  66: {
    one_liner: "Graph database with HTTP/Bolt drivers and Aura cloud.",
    auth: ["Basic", "Token", "Other"],
    access: "self_serve",
    access_detail: "Aura free tier or self-host Community Edition.",
    api_surface: "HTTP API + Bolt/Cypher",
    api_breadth: "moderate",
    mcp: "community",
    mcp_detail: "Community Neo4j MCP servers exist.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://neo4j.com/docs/http-api/current/"],
    confidence: 0.9,
  },
  67: {
    one_liner: "Cloud data warehouse with SQL API and connectors.",
    auth: ["OAuth2", "Other", "Token"],
    access: "trial_or_paid_self_serve",
    access_detail: "Trial accounts; key-pair/OAuth for programmatic access.",
    api_surface: "SQL API + drivers (broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No primary official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://docs.snowflake.com/en/developer-guide/sql-api/index"],
    confidence: 0.9,
  },
  68: {
    one_liner: "Managed MongoDB with Atlas Admin API.",
    auth: ["OAuth2", "API key", "Other"],
    access: "self_serve",
    access_detail: "Free M0 cluster; API keys / service accounts.",
    api_surface: "REST Admin API + driver APIs",
    api_breadth: "broad",
    mcp: "official",
    mcp_detail: "MongoDB has been shipping MCP server tooling.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://www.mongodb.com/docs/atlas/configure-api-access/"],
    confidence: 0.93,
  },
  69: {
    one_liner: "Observability platform (metrics, logs, APM) with full HTTP API.",
    auth: ["API key"],
    access: "trial_or_paid_self_serve",
    access_detail: "API and app keys from org settings; free trial.",
    api_surface: "REST (very broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP focus.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://docs.datadoghq.com/api/latest/"],
    confidence: 0.94,
  },
  70: {
    one_liner: "Error monitoring and performance platform.",
    auth: ["Token", "OAuth2"],
    access: "self_serve",
    access_detail: "Auth tokens; free developer plan.",
    api_surface: "REST (moderate–broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP required.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://docs.sentry.io/api/auth/"],
    confidence: 0.94,
  },
  71: {
    one_liner: "All-in-one workspace with pages, DBs, and public API.",
    auth: ["OAuth2", "Token"],
    access: "self_serve",
    access_detail: "Internal integrations / OAuth free.",
    api_surface: "REST (moderate–broad)",
    api_breadth: "broad",
    mcp: "official",
    mcp_detail: "Notion official MCP connector.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developers.notion.com/docs/authorization"],
    confidence: 0.96,
  },
  72: {
    one_liner: "Spreadsheet-database hybrid with REST/metadata APIs.",
    auth: ["OAuth2", "Token"],
    access: "self_serve",
    access_detail: "Personal access tokens / OAuth; free workspace.",
    api_surface: "REST (moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://airtable.com/developers/web/api/authentication"],
    confidence: 0.94,
  },
  73: {
    one_liner: "Issue tracking for software teams with GraphQL API.",
    auth: ["OAuth2", "API key"],
    access: "self_serve",
    access_detail: "Personal API keys; free for small teams.",
    api_surface: "GraphQL (broad product surface)",
    api_breadth: "broad",
    mcp: "official",
    mcp_detail: "Linear supports MCP / agent integrations.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developers.linear.app/docs/graphql/working-with-the-graphql-api"],
    confidence: 0.95,
  },
  74: {
    one_liner: "Atlassian issue tracker with Cloud REST APIs.",
    auth: ["OAuth2", "Basic", "Token"],
    access: "self_serve",
    access_detail: "Free Jira Cloud; API tokens + OAuth 3LO.",
    api_surface: "REST (very broad)",
    api_breadth: "broad",
    mcp: "official",
    mcp_detail: "Atlassian remote MCP for Cloud products.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/"],
    confidence: 0.95,
  },
  75: {
    one_liner: "Work management / tasks platform.",
    auth: ["OAuth2", "Token"],
    access: "self_serve",
    access_detail: "Developer app + PATs; free tier.",
    api_surface: "REST (broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP required.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developers.asana.com/docs/authentication"],
    confidence: 0.94,
  },
  76: {
    one_liner: "Work OS boards with GraphQL API.",
    auth: ["OAuth2", "API key"],
    access: "self_serve",
    access_detail: "API token from developer section; free plan limited.",
    api_surface: "GraphQL (broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developer.monday.com/api-reference/docs/authentication"],
    confidence: 0.93,
  },
  77: {
    one_liner: "Productivity suite with tasks, docs, and chat APIs.",
    auth: ["OAuth2", "API key", "Token"],
    access: "self_serve",
    access_detail: "Personal tokens; free forever plan includes API.",
    api_surface: "REST (broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://clickup.com/api/developer-portal/authentication/"],
    confidence: 0.93,
  },
  78: {
    one_liner: "Doc-as-app platform with REST API.",
    auth: ["API key", "Token"],
    access: "self_serve",
    access_detail: "API tokens from account settings.",
    api_surface: "REST (moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://coda.io/developers/apis/v1"],
    confidence: 0.92,
  },
  79: {
    one_liner: "Work management sheets with enterprise API.",
    auth: ["OAuth2", "API key", "Token"],
    access: "trial_or_paid_self_serve",
    access_detail: "Developer account / API access with Smartsheet plan.",
    api_surface: "REST (broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://smartsheet.redoc.ly/"],
    confidence: 0.9,
  },
  80: {
    one_liner: "Time tracking and invoicing API.",
    auth: ["OAuth2", "Token"],
    access: "self_serve",
    access_detail: "Personal access tokens; free trial of Harvest.",
    api_surface: "REST (moderate)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://help.getharvest.com/api-v2/authentication-api/authentication/authentication/"],
    confidence: 0.92,
  },
  81: {
    one_liner: "Payments infrastructure with best-in-class API docs.",
    auth: ["API key", "OAuth2"],
    access: "self_serve",
    access_detail: "Test mode keys instantly; Connect OAuth for platforms.",
    api_surface: "REST (very broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP required.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://docs.stripe.com/keys"],
    confidence: 0.98,
  },
  82: {
    one_liner: "Bank account linking and financial data API.",
    auth: ["API key", "OAuth2", "Other"],
    access: "self_serve",
    access_detail: "Sandbox keys self-serve; Production requires application.",
    api_surface: "REST (broad fintech)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "partial",
    blocker: "Production access is application-gated (sandbox is easy).",
    evidence: ["https://plaid.com/docs/api/"],
    confidence: 0.94,
  },
  83: {
    one_liner: "Crypto exchange public & signed trading APIs.",
    auth: ["API key", "Other"],
    access: "self_serve",
    access_detail: "Create API keys on Binance account (KYC may apply by region).",
    api_surface: "REST + WebSocket (broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://binance-docs.github.io/apidocs/spot/en/#api-key-restrictions"],
    confidence: 0.92,
  },
  84: {
    one_liner: "Paygent Connect — payment gateway stack powered by NMI.",
    auth: ["API key", "Other", "Basic"],
    access: "partner",
    access_detail: "Merchant/gateway credentials via Paygent/NMI onboarding — not a public consumer API brand.",
    api_surface: "NMI/Collect.js style gateway APIs",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No Paygent-branded MCP.",
    buildability: "blocked",
    blocker: "Merchant underwriting / partner onboarding required; thin public Paygent-specific docs.",
    evidence: ["https://secure.nmi.com/merchants/resources/integration/integration_portal.php"],
    confidence: 0.7,
  },
  85: {
    one_liner: "iPayX AI payments / docs surface (emerging).",
    auth: ["API key", "Token"],
    access: "unclear",
    access_detail: "Public docs URL referenced; access model not clearly self-serve from open web alone.",
    api_surface: "Documented API (verify live)",
    api_breadth: "narrow_or_unclear",
    mcp: "none_found",
    mcp_detail: "No known official MCP.",
    buildability: "partial",
    blocker: "Sparse public evidence; needs human confirmation of credential path.",
    evidence: ["https://ipayx.ai/docs"],
    confidence: 0.55,
  },
  86: {
    one_liner: "Intuit QuickBooks Online accounting API.",
    auth: ["OAuth2"],
    access: "self_serve",
    access_detail: "Intuit Developer account + sandbox company free.",
    api_surface: "REST (broad accounting)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developer.intuit.com/app/developer/qbo/docs/get-started"],
    confidence: 0.94,
  },
  87: {
    one_liner: "Xero cloud accounting API.",
    auth: ["OAuth2"],
    access: "self_serve",
    access_detail: "Xero developer app + demo company.",
    api_surface: "REST (broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developer.xero.com/documentation/guides/oauth2/overview/"],
    confidence: 0.94,
  },
  88: {
    one_liner: "Brex corporate card and spend platform API.",
    auth: ["OAuth2", "Token"],
    access: "admin",
    access_detail: "Customer users can create tokens; partners need Brex-issued client credentials.",
    api_surface: "REST (moderate–broad)",
    api_breadth: "broad",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "partial",
    blocker: "Needs Brex customer account (or partner approval) — no free public sandbox for outsiders.",
    evidence: ["https://developer.brex.com/", "https://developer.brex.com/guides/partner_authentication"],
    confidence: 0.9,
  },
  89: {
    one_liner: "Ramp spend management Developer API + Developer MCP.",
    auth: ["OAuth2"],
    access: "admin",
    access_detail: "Admin creates developer app; sandbox is not fully self-serve (contact AM).",
    api_surface: "REST + Developer MCP",
    api_breadth: "broad",
    mcp: "official",
    mcp_detail: "Ramp Developer MCP (evolving; feedback via support ticket).",
    buildability: "partial",
    blocker: "Requires Ramp business admin; sandbox provisioning may need account manager.",
    evidence: ["https://docs.ramp.com/developer-api/v1/overview/introduction", "https://support.ramp.com/accessing-the-developer-api"],
    confidence: 0.91,
  },
  90: {
    one_liner: "Private market / company research data API.",
    auth: ["API key", "Token"],
    access: "partner",
    access_detail: "Standalone contract with Direct Data team; not included with platform seat alone.",
    api_surface: "REST (research data)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "blocked",
    blocker: "Sales/contract gate for API — correct finding, not a research failure.",
    evidence: ["https://pitchbook.com/help/PitchBook-api"],
    confidence: 0.93,
  },
  91: {
    one_liner: "NotebookLM / Gemini Enterprise notebook research surfaces.",
    auth: ["OAuth2", "Other"],
    access: "partner",
    access_detail: "Enterprise/Gemini Cloud path — not a simple consumer NotebookLM public API.",
    api_surface: "Gemini Enterprise / Vertex-adjacent (not classic NotebookLM consumer API)",
    api_breadth: "narrow_or_unclear",
    mcp: "none_found",
    mcp_detail: "No simple public NotebookLM MCP for agents.",
    buildability: "blocked",
    blocker: "No clear self-serve public NotebookLM API equivalent to other toolkits.",
    evidence: ["https://cloud.google.com/gemini/enterprise/docs"],
    confidence: 0.72,
  },
  92: {
    one_liner: "Meeting transcription product with hosted MCP server.",
    auth: ["OAuth2"],
    access: "trial_or_paid_self_serve",
    access_detail: "MCP via OAuth at mcp.otter.ai; public REST API key path limited — contact support for app embedding.",
    api_surface: "Official MCP (primary); limited public REST",
    api_breadth: "moderate",
    mcp: "official",
    mcp_detail: "https://mcp.otter.ai/mcp — OAuth; may require Business plan.",
    buildability: "partial",
    blocker: "MCP-first; classic REST toolkit may need partner/support path.",
    evidence: ["https://help.otter.ai/hc/en-us/articles/35287607569687-Otter-MCP-Server"],
    confidence: 0.88,
  },
  93: {
    one_liner: "AI meeting recorder with public API keys.",
    auth: ["API key"],
    access: "self_serve",
    access_detail: "Generate API key in Fathom settings → API Access.",
    api_surface: "REST; community MCP wrappers",
    api_breadth: "moderate",
    mcp: "community",
    mcp_detail: "Community Fathom MCP (API key); official REST exists.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://developers.fathom.ai/", "https://github.com/jerichosequitin/fathom-ai-mcp"],
    confidence: 0.9,
  },
  94: {
    one_liner: "AI search engine for scientific papers.",
    auth: ["OAuth2", "API key"],
    access: "partner",
    access_detail: "API access historically request/waitlist oriented (OAuth requested).",
    api_surface: "API (research search) — confirm current status",
    api_breadth: "narrow",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "partial",
    blocker: "Access appears request-gated; verify current developer onboarding.",
    evidence: ["https://consensus.app/home/blog/consensus-api/"],
    confidence: 0.7,
  },
  95: {
    one_liner: "Document parsing / OCR-for-LLMs API.",
    auth: ["API key"],
    access: "self_serve",
    access_detail: "API keys from Reducto dashboard; usage-based.",
    api_surface: "REST (document parse)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No official MCP required.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://docs.reducto.ai/"],
    confidence: 0.9,
  },
  96: {
    one_liner: "Cognition Devin software engineering agent with API/MCP docs.",
    auth: ["API key", "Token", "OAuth2"],
    access: "partner",
    access_detail: "Product access is gated; docs.devin.ai covers API/MCP for customers.",
    api_surface: "API + MCP (agent sessions)",
    api_breadth: "moderate",
    mcp: "official",
    mcp_detail: "Devin documents MCP-oriented agent interfaces.",
    buildability: "partial",
    blocker: "Product access / seat gate before toolkit can be exercised.",
    evidence: ["https://docs.devin.ai/"],
    confidence: 0.8,
  },
  97: {
    one_liner: "AI content / video generation suite with CLI docs.",
    auth: ["API key", "Token"],
    access: "self_serve",
    access_detail: "CLI/API key oriented developer surface (confirm plan limits).",
    api_surface: "CLI / API (content generation)",
    api_breadth: "moderate",
    mcp: "none_found",
    mcp_detail: "No known official MCP.",
    buildability: "partial",
    blocker: "Docs maturity / auth details need live confirmation per plan.",
    evidence: ["https://docs.higgsfield.ai/", "https://higgsfield.ai/cli"],
    confidence: 0.68,
  },
  98: {
    one_liner: "Local CLI to render Mermaid diagrams to images/SVG.",
    auth: ["Other"],
    access: "self_serve",
    access_detail: "Open-source npm package — no cloud credentials.",
    api_surface: "CLI (local process)",
    api_breadth: "narrow",
    mcp: "community",
    mcp_detail: "Natural fit as a local skill/MCP tool wrapper.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://github.com/mermaid-js/mermaid-cli"],
    confidence: 0.97,
  },
  99: {
    one_liner: "Third-party YouTube transcript fetching API.",
    auth: ["API key"],
    access: "self_serve",
    access_detail: "API key from transcriptapi.com signup.",
    api_surface: "REST (narrow — transcripts)",
    api_breadth: "narrow",
    mcp: "none_found",
    mcp_detail: "No official MCP.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://transcriptapi.com/docs"],
    confidence: 0.88,
  },
  100: {
    one_liner: "AI meeting notes for sales teams with official MCP.",
    auth: ["OAuth2", "API key"],
    access: "trial_or_paid_self_serve",
    access_detail: "Grain workspace; MCP OAuth at api.grain.com/_/mcp.",
    api_surface: "REST + official MCP",
    api_breadth: "moderate",
    mcp: "official",
    mcp_detail: "Official Grain MCP (OAuth) — meetings, notes, transcripts.",
    buildability: "ready",
    blocker: null,
    evidence: ["https://docs.grain.com/", "https://api.grain.com/_/mcp"],
    confidence: 0.9,
  },
};
